######################################################################
# Automatically generated by qmake (2.01a) Tue May 27 10:30:56 2014
######################################################################

TEMPLATE = app
TARGET = 
DEPENDPATH += .
INCLUDEPATH += .

# Input
SOURCES += Source.cpp
