######################################################################
# Automatically generated by qmake (2.01a) Tue May 27 10:30:56 2014
######################################################################

TEMPLATE = app
TARGET = 
DEPENDPATH += . coroutine promise
INCLUDEPATH += .

# Input
SOURCES += taskpool.cpp \
coroutine/coroutine.cpp \
coroutine/coroutineschedule.cpp \
coroutine/task.cpp \
promise/deferredbase.cpp \
promise/deferreddata.cpp

